// Generated by CoffeeScript 1.6.2
var name, should;

should = require('should');

name = "yaoyi";

describe('test', function() {
  return it('name should be yaoyi', function() {
    return name.should.be.eql("yaoyi");
  });
});
